### ISSUE TITLE
Scene switching: Results screen too small

### ISSUE THREAD

**Issue by FYPetro** [OsuCelebrity/OsuCelebrity#43]
![image](https://cloud.githubusercontent.com/assets/5100887/12706006/aea08ea8-c838-11e5-9d99-03daeff8a47a.png)

GIve a timeout time for the result screen before switching to the slideshow.

**Comment by FYPetro** [comment]
> Samshirley00: When it changes scene, the total queued gets hidden, any chance of moving it slightly

status: confirming

**Comment by RedbackThomson** [comment]
@Tillerino @reesebiz Where in the project has the switch to this result screen been implemented?

**Comment by FYPetro** [comment]
a.k.a. @reesebiz said: add a buffer @Tillerino

**Comment by Tillerino** [comment]
This isn't how any of this works. The scene is switched when we start spectating a new player. It is  unlikely that we are in the result screen when that happens and even more unlikely that we have been there for a short time. Furthermore, we have no idea that we are in the result screen and would have to put in quite some work to detect that.

Since the effort far outweighs the impact here, I'll just close this.
